In [1]:
import numpy as np

In [2]:
#creating an array of range 10
a = np.arange(10)
print (a)

[0 1 2 3 4 5 6 7 8 9]


In [3]:
#1.Reshape: Gives a new shape to an array,without changing data

#reshaping the array to be 2D in nature
b = a.reshape(5,2)
print (b)


[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [4]:
#2.	Flat, flatten: Returns a copy of the array collapsed into one dimension

#the flat function: behaves similar to Python's iterator
f = np.arange(0,10,3).reshape(2,2)
print (f)
print('The flat function:')
print (f.flat[3])

[[0 3]
 [6 9]]
The flat function:
9


In [5]:
#Flattening an array
f1 = f.flatten()
print(f1)

[0 3 6 9]


In [9]:
#Flattening an array with a custom ordering
f2 = f.flatten(order = 'F')
print(f2)


[0 6 3 9]
[[0 3]
 [6 9]]


In [10]:
#flatten returns a copy whereas ravel returns a view of the original
#if you modify a ravel(), it may change the elements of the original array
#this doesnt happen with flatten()
f3 = f.ravel()
print(f3)




[0 3 6 9]


In [11]:
#3.	Transpose: Permutes the dimensions of an array

t = np.arange(9).reshape(3,3)
print (t)
print ('\n The transpose is:')
print (np.transpose(t))

[[0 1 2]
 [3 4 5]
 [6 7 8]]

 The transpose is:
[[0 3 6]
 [1 4 7]
 [2 5 8]]


In [18]:
#4.	Broadcast_to: Broadcasts an array to a new shape

arr = np.arange(5)
print('original:')
print (arr)
br = np.broadcast_to(arr, (5,5))
print('\n broadcast:')
print(br)

original:
[0 1 2 3 4]

 broadcast:
[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


In [23]:
#5.	Concatenate: Joins a sequence of arrays along an existing axis

a1 = np.array([['a','b'],['c','d']])
a2 = np.array([['e','f'],['g','h']])

print ('Array 1 : \n', a1)
print ('Array 2 : \n', a2)
print ('\n')
print('joining along axis 0 : \n')
print(np.concatenate((a1,a2)), '\n')
print('joining along axis 1 : \n')
print(np.concatenate((a1,a2), axis = 1))

Array 1 : 
 [['a' 'b']
 ['c' 'd']]
Array 2 : 
 [['e' 'f']
 ['g' 'h']]


joining along axis 0 : 

[['a' 'b']
 ['c' 'd']
 ['e' 'f']
 ['g' 'h']] 

joining along axis 1 : 

[['a' 'b' 'e' 'f']
 ['c' 'd' 'g' 'h']]


In [48]:
#6.	Stacking: Joins a sequence of arrays along a new axis

print('stacking along axis 0 : \n')
print(np.stack((a1,a2)), '\n')
print('stacking along axis 1 : \n')
print(np.stack((a1,a2), axis = 1))

stacking along axis 0 : 

[[['a' 'b']
  ['c' 'd']]

 [['e' 'f']
  ['g' 'h']]] 

stacking along axis 1 : 

[[['a' 'b']
  ['e' 'f']]

 [['c' 'd']
  ['g' 'h']]]


In [25]:
#horizontal stacking vs vertical stacking: replicates concatenating
print('vertical stacking: \n')
print(np.vstack((a1,a2)), '\n')
print('horizontal stacking: \n')
print(np.hstack((a1,a2)))


vertical stacking: 

[['a' 'b']
 ['c' 'd']
 ['e' 'f']
 ['g' 'h']] 

horizontal stacking: 

[['a' 'b' 'e' 'f']
 ['c' 'd' 'g' 'h']]


In [41]:
#7.	Splitting: Splits an array into multiple sub-arrays

arr2 = np.arange(10)
s = np.split(arr2, 2)
print('\n original:', arr2)
print('\n split in 2 equal parts: \n', s)


 original: [0 1 2 3 4 5 6 7 8 9]

 split in 2 equal parts: 
 [array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]


In [42]:
#horizontal vs vertical array splitting

arr3 = np.arange(16).reshape(4,4)
vs = np.vsplit(arr3,2)
hs = np.hsplit(arr3,2)
print('original: \n', arr3, '\n')
print('vertical splitting: \n',vs, '\n')
print('horizontal splitting: \n',hs)

original: 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]] 

vertical splitting: 
 [array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])] 

horizontal splitting: 
 [array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]


In [43]:
#8.	Resizing: Returns a new array with the specified shape

x = np.array([[1,2],[3,4],[5,6]])
rs1 = np.resize(x,(2,3))
rs2 = np.resize(x, (3,3))
#take note of what happens to rs2
print('original: \n', x, '\n')
print('resized to shape(2,3): \n', rs1, '\n')
print('resized to shape(3,3): \n', rs2)

original: 
 [[1 2]
 [3 4]
 [5 6]] 

resized to shape(2,3): 
 [[1 2 3]
 [4 5 6]] 

resized to shape(3,3): 
 [[1 2 3]
 [4 5 6]
 [1 2 3]]


In [44]:
#9.	Appending: Appends the values to the end of an array

ap0 = np.append(x,[7,8])
ap1 = np.append(x,[[7,8]], axis=0)
ap2 = np.append(x,[[1,1],[2,2],[3,3]], axis =1)
print('original: \n', x, '\n')
print('simple append: \n', ap0, '\n')
print('append along axis 0: \n', ap1, '\n')
print('append along axis 1: \n', ap2, '\n')


original: 
 [[1 2]
 [3 4]
 [5 6]] 

simple append: 
 [1 2 3 4 5 6 7 8] 

append along axis 0: 
 [[1 2]
 [3 4]
 [5 6]
 [7 8]] 

append along axis 1: 
 [[1 2 1 1]
 [3 4 2 2]
 [5 6 3 3]] 



In [45]:
#10.	Inserting: Inserts the values along the given axis before the given indices 

z = np.array([[1,2],[3,4],[5,6]]) 
#note what happens if you dont pass a parameter
ins = np.insert(z,3,[11,12])
#insertion along axis 0
ins2 = np.insert(z,1,[11],axis = 0)
#insertion along axis 1
ins3 = np.insert(z,1,11,axis = 1)
print ('First array:' )
print (z) 
print ('\n')  

print ('Axis parameter not passed. The input array is flattened before insertion.')
print (ins) 
print ('\n')  
print ('Axis parameter passed. The values array is broadcast to match input array.')
print ('\n') 
print ('Insertion along axis 0:') 
print (ins2 )
print ('\n')  

print ('Insertion along axis 1:') 
print (ins3)

First array:
[[1 2]
 [3 4]
 [5 6]]


Axis parameter not passed. The input array is flattened before insertion.
[ 1  2  3 11 12  4  5  6]


Axis parameter passed. The values array is broadcast to match input array.


Insertion along axis 0:
[[ 1  2]
 [11 11]
 [ 3  4]
 [ 5  6]]


Insertion along axis 1:
[[ 1 11  2]
 [ 3 11  4]
 [ 5 11  6]]


In [48]:
#11.	Deleting:

print ('First array:' )
print (z) 
print ('\n') 

del1 = np.delete(z,1)
del2 = np.delete(z,1, axis=0)
del3 = np.delete(z,1, axis=1)
print ('Axis parameter not passed. Array is flattened before deletion.')
print (del1) 
print ('\n')  
print ('Axis parameter passed.')
print ('Deletion along axis 0: Row 2 deleted') 
print (del2 )
print ('\n')
print ('Axis parameter passed. ')
print ('Deletion along axis 1: Column 2 deleted') 
print (del3)



First array:
[[1 2]
 [3 4]
 [5 6]]


Axis parameter not passed. Array is flattened before deletion.
[1 3 4 5 6]


Axis parameter passed.
Deletion along axis 0: Row 2 deleted
[[1 2]
 [5 6]]


Axis parameter passed. 
Deletion along axis 1: Column 2 deleted
[[1]
 [3]
 [5]]
