In [1]:
import numpy as np

In [2]:
#CREATING ARRAYS

#There are three different ways to create Numpy arrays:

#●	Using Numpy functions
#●	Conversion from other Python structures like lists
#●	Using special library functions

#Numpy functions

#Since Numpy functions have in built creating arrays. You can create one-dimensional array, two-dimensional array, creating three-dimensional and beyond. 
#●	Creating a one-dimensional array

#Passing a value 20 to the arange function creates an array with values ranging from 0 to 19.


In [3]:
array = np.arange(20)
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [4]:
#to verify if its a one dimensional array
array.shape

(20,)

In [5]:
#The fact that there is no value after the comma means that there it is in fact a one dimensional array. 

#●	Creating two-dimensional array

array = np.arange(20).reshape(4,5)
array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [6]:
#The reshape() function is used to convert the array into a 2D by defining it using 4 rows and 5 columns. 
#●	Creating three-dimensional arrays

array = np.arange(27).reshape(3,3,3)
array


array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [7]:
#Once these arrays have been defined, in the event that you want to access an element in the mentioned arrays, the following syntaxes can be used:

#	1D Array : array[index position]
#	2D Array:  array[index position, array position]

#●	Other Numpy functions
#Other than arange you can also use :



In [8]:
#1. zero array
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
#2. ones array
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [12]:
#3. empty array: creates an array that is random and depends on the state of the memory.
np.empty((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [13]:
#4. full: creates a n * n array filled with the given value.
np.full((2,2),3)

array([[3, 3],
       [3, 3]])

In [14]:
#5. eye array: creates a n * n array filled with the given value.
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [15]:
#6. Linspace: returns evenly spaced numbers over a specified interval.
np.linspace(0,10,num=4)

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [16]:
#Conversion from other Python structures like lists
#This procedure involves you creating the list and then passing its variable name to create a Numpy.

list = [4,5,6]
list

[4, 5, 6]

In [17]:
array = np.array(list)
array

array([4, 5, 6])

In [18]:
#Using special library functions

#To create an array with filled random values between 0 and 1, you can use random(). 

np.random.random((2,2))

array([[0.36842764, 0.76586665],
       [0.09930049, 0.36743838]])