# NUMPY TUTORIALS

In [1]:
#Import the numpy library
import numpy as np

In [3]:
#To change a list into an array
seq = [1,2,3,4,5,65,34,5]

arr = np.array(seq)

In [4]:
print(type(arr))
#This now displays its no longer a list but an array

<class 'numpy.ndarray'>


In [6]:
#To create a range of numbers in array
np.arange(0,10,1)

#Where the first number shows the lower limit the next shows the highest limit and the final shows the stepping space

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
#To generate an array of zeros
np.zeros(3)

array([0., 0., 0.])

In [10]:
np.zeros((10,10))
#The first param shows the rows then the nest shows the number of columns

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [11]:
#To generate an array of ones
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [12]:
np.ones((10,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [13]:
# To generate an array with evenly spaced numbers over a specified interval
np.linspace(0,100,11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [14]:
#To create an identity matrix
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [17]:
# To generate an array with uniform distirbution between 0 and 1
np.random.rand(10)

array([0.97070031, 0.97908185, 0.81858672, 0.49737358, 0.36172788,
       0.97141965, 0.11947356, 0.09725549, 0.55424151, 0.23806919])

In [20]:
#Similar to above but in 2D
np.random.rand(10,10)

array([[0.35587859, 0.55021087, 0.43174825, 0.99989446, 0.63999571,
        0.80450699, 0.34062586, 0.64642553, 0.9258373 , 0.52480074],
       [0.33923987, 0.13764594, 0.65164892, 0.60813983, 0.08247266,
        0.76158367, 0.27868761, 0.33792041, 0.76104876, 0.78415155],
       [0.91743434, 0.62647446, 0.89877509, 0.81046398, 0.52623266,
        0.09174508, 0.05358742, 0.60259903, 0.55140423, 0.99862415],
       [0.9788285 , 0.7391122 , 0.0826305 , 0.64648107, 0.84526404,
        0.53365962, 0.65886973, 0.71401022, 0.3950776 , 0.04340071],
       [0.63989094, 0.87308466, 0.17036739, 0.00415184, 0.011346  ,
        0.43845174, 0.09223963, 0.38881709, 0.17519012, 0.06403979],
       [0.77585125, 0.25037596, 0.86826714, 0.8250774 , 0.40574006,
        0.12178305, 0.99995234, 0.18092431, 0.33739432, 0.21617273],
       [0.64617938, 0.55506717, 0.18779501, 0.76167471, 0.53627118,
        0.31159159, 0.76489344, 0.45391181, 0.39602226, 0.40040045],
       [0.93825072, 0.96489034, 0.6750713

In [21]:
#To generate random numbers in a standard normal distribution
np.random.randn(10)

array([ 0.47258567,  0.68034431,  0.32201034, -0.45845239,  0.40444209,
       -0.91604745, -0.10145412,  0.45196458, -0.21845852, -1.08199458])

In [22]:
#Similar to above but in 2D
np.random.randn(10,10)

array([[ 1.36625709, -1.03357727,  0.67324552,  0.05854123, -0.24194427,
         0.17962267,  0.80970237,  0.76902919,  1.0274995 ,  1.69604101],
       [ 0.01762061,  0.07024614,  0.07004641,  0.60303154, -0.83411813,
        -1.03122995, -0.75517982, -2.27060132, -2.00827638,  1.71808849],
       [-1.00149878, -0.37476083, -1.19263562, -1.00031868,  1.13709721,
        -1.60087426,  0.76065927,  1.91292259, -1.19625496,  0.13653959],
       [ 0.75911625, -1.32913999, -2.10323908, -0.88520768, -1.23819871,
        -1.54671085, -0.64725632, -1.12826318, -0.78113244,  2.40029917],
       [ 0.23260613, -2.0667973 ,  0.70476472,  1.33678769, -0.5526812 ,
        -0.75489541, -1.60303788, -1.54864068, -2.76993756, -3.14520762],
       [-0.18567877, -0.58527601, -0.85915406,  0.20784078,  0.26821351,
         1.47068167, -0.19739117, -1.02035421, -0.07430237, -0.75628766],
       [-0.48997689,  0.13274176, -0.74670862, -0.74421797,  0.41085429,
         0.90234275, -0.06527599,  1.2515487 

In [24]:
#To generate random integers
np.random.randint(0,100,10)
#Where the first param is the lowest value the next is the highest then the final is number of random attributes

array([ 8, 89, 28, 61, 89, 97,  5, 30, 50, 83])

In [28]:
x = np.random.randint(0,100,100)

In [30]:
#You can know the size of the matrix by 
x.shape

(100,)

In [32]:
#Then you can reshape x by
x.reshape(10,10)

#The matrix has to be full or else an error will be generated

array([[22, 25,  2, 10, 53, 68,  6, 18, 20, 37],
       [58,  4, 16, 35,  8, 18, 97, 78, 74, 36],
       [89, 64, 48, 68,  8, 45, 48, 12, 83, 76],
       [93, 39, 31, 38, 46, 32, 88, 35, 87, 87],
       [31, 39, 26, 54, 96, 27, 11, 19, 49, 72],
       [35, 74, 92, 34, 29, 57,  4, 81, 16, 58],
       [25, 65, 81, 33, 37, 27, 57, 10, 37, 20],
       [35, 91, 27, 83, 67, 85,  7, 19, 69, 77],
       [84, 46, 46, 62, 86, 67, 91, 60, 87, 61],
       [ 1, 32, 65, 93, 57,  6, 58, 27, 18, 98]])

In [33]:
#To get the max value of an array
x.max()

98

In [34]:
#To get the min value of an array
x.min()

1

In [35]:
#To get the index location of the maximum value
x.argmax()

99

In [37]:
#To get the index location of the maximum value
x.argmin()

90

# PART TWO NUMPY INDEXING AND SELECTION

In [40]:
#To get the exact location of a certain index
x[2]

2

In [42]:
#Slice notation gives you the list from the specified indexes
x[0:10]

array([22, 25,  2, 10, 53, 68,  6, 18, 20, 37])

In [47]:
#To create a copy of the array
y = x.copy()

In [48]:
y

array([22, 25,  2, 10, 53, 68,  6, 18, 20, 37, 58,  4, 16, 35,  8, 18, 97,
       78, 74, 36, 89, 64, 48, 68,  8, 45, 48, 12, 83, 76, 93, 39, 31, 38,
       46, 32, 88, 35, 87, 87, 31, 39, 26, 54, 96, 27, 11, 19, 49, 72, 35,
       74, 92, 34, 29, 57,  4, 81, 16, 58, 25, 65, 81, 33, 37, 27, 57, 10,
       37, 20, 35, 91, 27, 83, 67, 85,  7, 19, 69, 77, 84, 46, 46, 62, 86,
       67, 91, 60, 87, 61,  1, 32, 65, 93, 57,  6, 58, 27, 18, 98])

In [50]:
#To access specific figures
z = np.arange(0,100)
z = z.reshape(10,10)
z

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [51]:
#If you want to access  44
z[4][4]

44

In [52]:
#Alternatively 
z[4,4]

44

# PART THREE NUMPY OPERATIONS

In [55]:
e = np.arange(0,10)
f = np.arange(10,20)

In [56]:
#One can be able to add arrays
e + f

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [57]:
#One can be able to subtract arrays
f -e

array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10])

In [58]:
#One can be able to multiply arrays
f * e

array([  0,  11,  24,  39,  56,  75,  96, 119, 144, 171])

In [60]:
#UNIVERSAL ARRAY FUNCTIONS
#TO FIND THE SQUARE ROOT
np.sqrt(e)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [61]:
#TO FIND THE EXPONENTIAL VALUES
np.exp(e)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [66]:
#TO FIND THE MAXIMUN VALUE IN AN ARRAY
np.max(e)

9

In [63]:
#TP FIND THE MINIMUM VALUE IN AN ARRAY
np.min(e)

0

In [64]:
#TO FIND THE SIN VALUE OF THE ARRAY
np.sin(e)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [65]:
#TO FIND THE LOG VALUE OF THE ARRAY
np.log(e)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])