In [1]:
import numpy as np

In [4]:
#creating an array of range 10
a = np.arange(10)
print (a)

[0 1 2 3 4 5 6 7 8 9]


In [6]:
#reshaping the array to be 2D in nature
b = a.reshape(5,2)
print (b)


[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [23]:
#the flat function: behaves similar to Python's iterator
f = np.arange(0,10,3).reshape(2,2)
print (f)
print('The flat function:')
print (f.flat[3])

[[0 3]
 [6 9]]
The flat function:
9


In [20]:
#Flattening an array
f1 = f.flatten()
print(f1)

[0 1 2 3 4 5 6 7 8 9]


In [26]:
#Flattening an array with a custom ordering
f2 = f.flatten(order = 'F')
print(f2)

[0 6 3 9]


In [28]:
#flatten returns a copy whereas ravel returns a view of the original
#if you modify a ravel(), it may change the elements of the original array
#this doesnt happen with flatten()
f3 = f.ravel()
print(f3)



[0 3 6 9]


In [33]:
#transpose an array
t = np.arange(9).reshape(3,3)
print (t)
print ('\n The transpose is:')
print (np.transpose(t))

[[0 1 2]
 [3 4 5]
 [6 7 8]]

 The transpose is:
[[0 3 6]
 [1 4 7]
 [2 5 8]]


In [41]:
#broadcasting
arr = np.arange(5)
print('original:')
print (arr)
br = np.broadcast_to(arr, (5,5))
print('\n broadcast:')
print(br)

original:
[0 1 2 3 4]

 broadcast:
[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


In [47]:
#concatenating arrays
a1 = np.array([['a','b'],['c','d']])
a2 = np.array([['e','f'],['g','h']])

print ('Array 1 : \n', a1)
print ('Array 2 : \n', a2)
print ('\n')
print('joining along axis 0 : \n')
print(np.concatenate((a1,a2)), '\n')
print('joining along axis 1 : \n')
print(np.concatenate((a1,a2), axis = 1))

Array 1 : 
 [['a' 'b']
 ['c' 'd']]
Array 2 : 
 [['e' 'f']
 ['g' 'h']]


joining along axis 0 : 

[['a' 'b']
 ['c' 'd']
 ['e' 'f']
 ['g' 'h']] 

joining along axis 1 : 

[['a' 'b' 'e' 'f']
 ['c' 'd' 'g' 'h']]


In [48]:
#stacking arrays
print('stacking along axis 0 : \n')
print(np.stack((a1,a2)), '\n')
print('stacking along axis 1 : \n')
print(np.stack((a1,a2), axis = 1))

stacking along axis 0 : 

[[['a' 'b']
  ['c' 'd']]

 [['e' 'f']
  ['g' 'h']]] 

stacking along axis 1 : 

[[['a' 'b']
  ['e' 'f']]

 [['c' 'd']
  ['g' 'h']]]


In [51]:
#horizontal stacking vs vertical stacking: replicates concatenating
print('vertical stacking: \n')
print(np.vstack((a1,a2)), '\n')
print('horizontal stacking: \n')
print(np.hstack((a1,a2)))


vertical stacking: 

[['a' 'b']
 ['c' 'd']
 ['e' 'f']
 ['g' 'h']] 

horizontal stacking: 

[['a' 'b' 'e' 'f']
 ['c' 'd' 'g' 'h']]


In [54]:
#splitting arrays
arr2 = np.arange(10)
s = np.split(arr2, 2)
print('\n original:', arr2)
print('\n split in 2 equal parts: \n', s)


 original: [0 1 2 3 4 5 6 7 8 9]

 split in 2 equal parts: 
 [array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]


In [56]:
#horizontal vs vertical array splitting
arr3 = np.arange(16).reshape(4,4)
vs = np.vsplit(arr3,2)
hs = np.hsplit(arr3,2)
print('original: \n', arr3, '\n')
print('vertical splitting: \n',vs, '\n')
print('horizontal splitting: \n',hs)

original: 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]] 

vertical splitting: 
 [array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])] 

horizontal splitting: 
 [array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]


In [58]:
#resizing arrays
x = np.array([[1,2],[3,4],[5,6]])
rs1 = np.resize(x,(3,2))
rs2 = np.resize(x, (3,3))
#take note of what happens to rs2
print('original: \n', x, '\n')
print('resized to shape(3,2): \n', rs1, '\n')
print('resized to shape(3,3): \n', rs2)

original: 
 [[1 2]
 [3 4]
 [5 6]] 

resized to shape(3,2): 
 [[1 2]
 [3 4]
 [5 6]] 

resized to shape(3,3): 
 [[1 2 3]
 [4 5 6]
 [1 2 3]]


In [62]:
#Appending to arrays
ap0 = np.append(x,[7,8])
ap1 = np.append(x,[[7,8]], axis=0)
ap2 = np.append(x,[[1,1],[2,2],[3,3]], axis =1)
print('original: \n', x, '\n')
print('simple append: \n', ap0, '\n')
print('append along axis 0: \n', ap1, '\n')
print('append along axis 1: \n', ap2, '\n')


original: 
 [[1 2]
 [3 4]
 [5 6]] 

simple append: 
 [1 2 3 4 5 6 7 8] 

append along axis 0: 
 [[1 2]
 [3 4]
 [5 6]
 [7 8]] 

append along axis 1: 
 [[1 2 1 1]
 [3 4 2 2]
 [5 6 3 3]] 



In [ ]:
#inserting 
